In [2]:
import sys
from PIL import Image
import numpy as np

In [9]:
input_path = '..\images\persons'
output_path = '..\images'

images = [Image.open(x).convert("RGBA") for x in [input_path + "\peep(" + str(x+1) + ").png" for x in range(18)]]
widths, heights = zip(*(i.size for i in images))

total_width = sum(widths)
max_height = max(heights)

new_im = Image.new('RGBA', (total_width, max_height))

x_offset = 0
for im in images:
  new_im.paste(im, (x_offset,0))
  x_offset += im.size[0]

new_im.save('hero.png')

In [ ]:
[x for x in range(10)]

In [5]:
inds = np.array([1, 3, 6, 8, 9, 10, 11, 12, 13, 14,
 15, 18, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29,
 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44,
 45, 46, 49, 50, 51, 52, 54, 55, 56, 57, 59,
 60, 62, 63, 65, 66, 67, 68, 69, 70, 71, 73,
 75, 76, 79, 80, 81, 83, 85, 87,
 94, 95, 96, 98, 99, 102, 103])
inds_bool = np.zeros(15*7)
inds_bool[inds] = True
vect2 = np.reshape(inds_bool, (-1, 7))
print(vect2)

[[0. 1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0.]
 [1. 1. 0. 0. 1. 1. 0.]]
